[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"  # Points to the folder containing serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/json-server"
  status = 200
